### ISSUE TITLE
Installation guidelines

### ISSUE THREAD

**Issue by ricardofrantz** [JuliaInv/MUMPSjInv.jl#25]
Hi,

Are there some installation guidelines to follow?
I downloaded the package and added it to Julia in MacOS, but I am facing an error when trying to call solveMUMPS:

```
ERROR: LoadError: could not load library "/Users/ricardofrantz/.julia/packages/MUMPSjInv/FsSIR/lib/MUMPS"
dlopen(/Users/ricardofrantz/.julia/packages/MUMPSjInv/FsSIR/lib/MUMPS.dylib, 0x0001): tried: '/Users/ricardofrantz/.julia/packages/MUMPSjInv/FsSIR/lib/MUMPS.dylib' (no such file)
```

Should I compile or download something else?

**Comment by dpo** [comment]
I'm not sure this package is still maintained. See https://github.com/JuliaSmoothOptimizers/MUMPS.jl for an up-to-date interface.

**Comment by lruthotto** [comment]
Thanks dpo. You're right that this package is not maintained any longer. I'll add a link to your package to the README.
